package controller.entity;

public enum EntityEnum {
	ABS_DATA_TYPE,
	ABS_RELATION,
	BASIC_SEARCH_ENTITY,
	CATEGORIZED_ENTITY,
	CATEGORIZED_RELATION,
	GEO_ENTITY,
	MOVIE_APPEARANCE,
	MOVIE_ENTITY,
	NAMED_ENTITY,
	NAMED_RELATION,
	PERSON_ENTITY
}
