package controller.enums;

public enum MovieDataEnum {
	MOVIE_AKAS,
	MOVIE_GOOFS,
	MOVIE_COUNTRIES,
	MOVIE_QUOTES,
	MOVIE_GENRES,
	MOVIE_CONNECTIONS,
	MOVIE_CAST,
	MOVIE_TRIVIA,
	MOVIE_LANGUAGES,
	MOVIE_CRAZY_CREDITS
}
