package controller.entity;

public enum EntityEnum {
	ABS_DATA_TYPE,
	RELATION,
	CATEGORIZED_ENTITY,
	CATEGORIZED_RELATION,
	GEO_ENTITY,
	CASTING_RELATION,
	NAMED_CASTING_RELATION,
	MOVIE_ENTITY,
	NAMED_ENTITY,
	NAMED_RELATION,
	PERSON_ENTITY
}
